shutdownPassword: test
gelflog:
  isEnabled: false
  host: http://lcoalhost:12201/gelf
  port: 12201
  version: 1.1
  facility: Spring REST Api Server
  extractStackTrace: true
  filterStackTrace: true
  timestampPattern: yyyy-MM-dd HH:mm:ss,SSSS
  maximumMessageSize: 8192
  level: INFO
server:
  ip: localhost